const ErrorCodes = {
  MALFORMED_JSON_ERROR_CODE: 88,
  RUNTIME_ERROR_CODE: 77,
  DB_ERROR: 66,
  ERROR_OCCURRED_WHEN_FETCHING_DATA_FROM_EXTERNAL: 55,
  VALIDATION_ERROR: 44
}

export default ErrorCodes;
